In [22]:
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup

In [23]:
url = 'https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&txtKeywords=machine+learning&txtLocation='

In [24]:
page = requests.get(url).text

In [25]:
soup = BeautifulSoup(page, 'lxml')

In [26]:
company_name = []
result = soup.select('li h3')
for r in range(len(result)):
    company_name.append(result[r].text.rstrip().strip('(More Jobs)').strip('\r\n'))
company_name

['    APPLYCUP HIRING SOLUTIONS LLP',
 '    corner stone solution',
 '    Maxgen Technologies',
 '    Maxgen Technologies',
 '    Maxgen Technologies',
 '    Maxgen Technologies',
 '    serendipity',
 '    Maxgen Technologies',
 '    Maxgen Technologies',
 '    Maxgen Technologies',
 '    Maxgen Technologies',
 '    Maxgen Technologies',
 '    Priyanka Vinayak',
 '    Priyanka Vinayak',
 '    Priyanka Vinayak',
 '    Priyanka Vinayak',
 '    TECHNOPARK TRIVANDRU',
 '    Cybage Software Pvt Ltd',
 '    pattern effects labs private limited',
 '    Vitrana',
 '    Cybage Software Pvt Ltd',
 '    e-con systems india pvt.ltd.',
 '    Cotocu',
 '    Cotocu',
 '    Nse IT Ltd']

In [27]:
result = soup.select('li span[class="srp-skills"]')
skills = [r.text.replace('\r\n', '').strip() for r in result]
skills

['image processing  ,  algorithms  ,  python  ,  c    ,  c  ,  natural language processing  ,  machine learning  ,  opencv',
 'algorithms  ,  bi  ,  image processing  ,  python  ,  natural language processing  ,  machine learning  ,  opencv',
 'freshers  ,  machine learning  ,  jobs',
 'machine learning  ,  panda',
 'internship  ,  machine learning  ,  ai',
 'hiring  ,  programming  ,  machine learning',
 'machine learning  ,  deep learning  ,  python',
 'machine learning  ,  Artificial Intelligence  ,  mca',
 'gujarat  ,  html  ,  machine learning  ,  ai',
 'internship  ,  python',
 'web  ,  programming  ,  machien learning  ,  internship',
 'developer  ,  machine leraning  ,  internship',
 'Finance  ,  Tally  ,  Tds  ,  Accounting  ,  Accountant  ,  assistant accountant',
 'Finance  ,  Tally  ,  Tds  ,  Accounting  ,  Accountant  ,  assistant accountant',
 'Finance  ,  Tally  ,  Tds  ,  Accounting  ,  Accountant  ,  assistant accountant',
 'Finance  ,  Tally  ,  Tds  ,  Accounting  ,  Accountant',
 'python  ,  machine learning  ,  opencv',
 'python  ,  java  ,  machine learning',
 'algorithms  ,  machine learning  ,   Boosting',
 'algorithms  ,  python  ,  machine learning',
 'algorithms  ,  python  ,  java  ,  machine learning',
 'algorithms  ,  c    ,  oops  ,  machine learning  ,  machine vision',
 'machine learning  ,  artificial intelligence  ,  docker',
 'machine learning  ,  docker  ,   data science',
 'algorithms  ,  python  ,  machine learning  ,  java  ,  data structures']

In [28]:
result = soup.select('ul[class="list-job-dtl clearfix"]')
job_descrip = [r.text.split('\n\n')[1].strip().replace('\r\n', '' ).replace('Job Description:', '') for r in result]
job_descrip[:5]

['Qualification : B.E. / M.E. / M.C.A. / B.Tech / M.Tech ( Any IT Background )  Experience : 1 - 2 YearsSkills : Tensor Flow ,  Keras ,  AWS ,  Lambda ,  MongolDB ,  Image Proce... More Details',
 'Machine Learning ,  Deep Learning ,  Python / R ,  Keras ,  Tensorflow ,  OpenCV ,  Regression ,  Clustering ,  AWS.Statistics  /  Mathematics: Data Quality Analysis ,  Data i... More Details',
 'Maxgen technologies pvt ltd offering internship in Ahmedabad. candidate will get live project internship in python , machine learning  , data science. What you achieve in inte... More Details',
 'Maxgen technologies pvt ltd offering internship in Ahmedabad. Candidates will get live project internship python  ,  machine learning  , ai. what we serve in an internship mul... More Details',
 'Maxgen technologies pvt ltd offering live project internship in Ahmedabad. we are offering an internship in Machine Leraning and Ai.why us?We offer live project. We provide lo... More Details']

In [29]:
result = soup.select('ul[class="top-jd-dtl clearfix"]')
result[:5]

[<ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>1 - 2 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Ahmedabad">Ahmedabad</span>
 </li>
 </ul>,
 <ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>3 - 6 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Indore,  Bengaluru / Bangalore">Indore,  Bengaluru / Bangalore</span>
 </li>
 </ul>,
 <ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>0 - 1 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Ahmedabad,  Mehsana,  Rajkot,  Surat,  Surendranagar">Ahmedabad,  Mehsana,  Rajkot,  Surat,  Surendranagar</span>
 </li>
 </ul>,
 <ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>0 - 1 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Ahmedabad,  Mehsana,  Rajkot,  Surat,  Surendranagar">Ahmedabad,  Mehsana,  Rajkot,  Surat,  Surendranagar</span>
 </li>
 </ul>,
 <ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>0 - 1 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Ahmedabad,  Bhavnagar,  Gandhinagar,  Jamnagar,  Mehsana">Ahmedabad,  Bhavnagar,  Gandhinagar,  Jamnagar,  Mehsana</span>
 </li>
 </ul>]

In [30]:
location = [r.text.split()[-1] for r in result]
location

['Ahmedabad',
 'Bangalore',
 'Surendranagar',
 'Surendranagar',
 'Mehsana',
 'Mehsana',
 'Bangalore',
 'Thane',
 'Surendranagar',
 'Surendranagar',
 'Solapur',
 'Solapur',
 'Jorhat',
 'Jorhat',
 'Dhubri',
 'Silchar',
 'Thiruvananthapuram',
 'Pune',
 'Bangalore',
 'Bangalore',
 'Pune',
 'Chennai',
 'Bangalore',
 'Bangalore',
 'Mumbai']

In [36]:
experience = soup.select('ul[class="top-jd-dtl clearfix"]')
experience[:5]

[<ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>1 - 2 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Ahmedabad">Ahmedabad</span>
 </li>
 </ul>,
 <ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>3 - 6 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Indore,  Bengaluru / Bangalore">Indore,  Bengaluru / Bangalore</span>
 </li>
 </ul>,
 <ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>0 - 1 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Ahmedabad,  Mehsana,  Rajkot,  Surat,  Surendranagar">Ahmedabad,  Mehsana,  Rajkot,  Surat,  Surendranagar</span>
 </li>
 </ul>,
 <ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>0 - 1 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Ahmedabad,  Mehsana,  Rajkot,  Surat,  Surendranagar">Ahmedabad,  Mehsana,  Rajkot,  Surat,  Surendranagar</span>
 </li>
 </ul>,
 <ul class="top-jd-dtl clearfix">
 <li><i class="material-icons">card_travel</i>0 - 1 yrs</li>
 <li>
 <i class="material-icons">location_on</i>
 <span title="Ahmedabad,  Bhavnagar,  Gandhinagar,  Jamnagar,  Mehsana">Ahmedabad,  Bhavnagar,  Gandhinagar,  Jamnagar,  Mehsana</span>
 </li>
 </ul>]

In [32]:
year_exp = [r.text.split('\n')[1].replace('card_travel', '') for r in experience]
year_exp

['1 - 2 yrs',
 '3 - 6 yrs',
 '0 - 1 yrs',
 '0 - 1 yrs',
 '0 - 1 yrs',
 '0 - 1 yrs',
 '4 - 9 yrs',
 '0 - 1 yrs',
 '0 - 1 yrs',
 '0 - 1 yrs',
 '0 - 1 yrs',
 '0 - 1 yrs',
 '0 - 2 yrs',
 '0 - 2 yrs',
 '0 - 2 yrs',
 '0 - 1 yrs',
 '3 - 4 yrs',
 '6 - 9 yrs',
 '2 - 5 yrs',
 '2 - 4 yrs',
 '6 - 9 yrs',
 '0 - 4 yrs',
 '8 - 11 yrs',
 '0 - 3 yrs',
 '2 - 3 yrs']

In [35]:
page_info = list(zip(company_name,skills,job_descrip,location,year_exp))
page_info[:5]

[('    APPLYCUP HIRING SOLUTIONS LLP',
  'image processing  ,  algorithms  ,  python  ,  c    ,  c  ,  natural language processing  ,  machine learning  ,  opencv',
  'Qualification : B.E. / M.E. / M.C.A. / B.Tech / M.Tech ( Any IT Background )  Experience : 1 - 2 YearsSkills : Tensor Flow ,  Keras ,  AWS ,  Lambda ,  MongolDB ,  Image Proce... More Details',
  'Ahmedabad',
  '1 - 2 yrs'),
 ('    corner stone solution',
  'algorithms  ,  bi  ,  image processing  ,  python  ,  natural language processing  ,  machine learning  ,  opencv',
  'Machine Learning ,  Deep Learning ,  Python / R ,  Keras ,  Tensorflow ,  OpenCV ,  Regression ,  Clustering ,  AWS.Statistics  /  Mathematics: Data Quality Analysis ,  Data i... More Details',
  'Bangalore',
  '3 - 6 yrs'),
 ('    Maxgen Technologies',
  'freshers  ,  machine learning  ,  jobs',
  'Maxgen technologies pvt ltd offering internship in Ahmedabad. candidate will get live project internship in python , machine learning  , data science. What you achieve in inte... More Details',
  'Surendranagar',
  '0 - 1 yrs'),
 ('    Maxgen Technologies',
  'machine learning  ,  panda',
  'Maxgen technologies pvt ltd offering internship in Ahmedabad. Candidates will get live project internship python  ,  machine learning  , ai. what we serve in an internship mul... More Details',
  'Surendranagar',
  '0 - 1 yrs'),
 ('    Maxgen Technologies',
  'internship  ,  machine learning  ,  ai',
  'Maxgen technologies pvt ltd offering live project internship in Ahmedabad. we are offering an internship in Machine Leraning and Ai.why us?We offer live project. We provide lo... More Details',
  'Mehsana',
  '0 - 1 yrs')]

In [34]:
page_df = pd.DataFrame(page_info,  columns=['comp_name','key_skills', 'job_description', 'location', 'years of exp'])
page_df

,comp_name,key_skills,job_description,location,years of exp
0,APPLYCUP HIRING SOLUTIONS LLP,"image processing , algorithms , python , ...",Qualification : B.E. / M.E. / M.C.A. / B.Tech ...,Ahmedabad,1 - 2 yrs
1,corner stone solution,"algorithms , bi , image processing , pyt...","Machine Learning , Deep Learning , Python / ...",Bangalore,3 - 6 yrs
2,Maxgen Technologies,"freshers , machine learning , jobs",Maxgen technologies pvt ltd offering internshi...,Surendranagar,0 - 1 yrs
3,Maxgen Technologies,"machine learning , panda",Maxgen technologies pvt ltd offering internshi...,Surendranagar,0 - 1 yrs
4,Maxgen Technologies,"internship , machine learning , ai",Maxgen technologies pvt ltd offering live proj...,Mehsana,0 - 1 yrs
5,Maxgen Technologies,"hiring , programming , machine learning",Maxgen technologies pvt ltd offering live proj...,Mehsana,0 - 1 yrs
6,serendipity,"machine learning , deep learning , python","Hands on experience in Python programming , ...",Bangalore,4 - 9 yrs
7,Maxgen Technologies,"machine learning , Artificial Intelligence ...",Maxgen technologies Pvt ltd offers live projec...,Thane,0 - 1 yrs
8,Maxgen Technologies,"gujarat , html , machine learning , ai",Maxgen Technologies Pvt Ltd offering LiveProje...,Surendranagar,0 - 1 yrs
9,Maxgen Technologies,"internship , python",Maxgen technologies pvt ltd offering internshi...,Surendranagar,0 - 1 yrs
10,Maxgen Technologies,"web , programming , machien learning , i...",Maxgen Technologies Pvt Ltd offering College P...,Solapur,0 - 1 yrs
11,Maxgen Technologies,"developer , machine leraning , internship",Maxgen Technologies Pvt Ltd offering College P...,Solapur,0 - 1 yrs
12,Priyanka Vinayak,"Finance , Tally , Tds , Accounting , A...","Remote Recruiter: As a remote Recruiter , you...",Jorhat,0 - 2 yrs
13,Priyanka Vinayak,"Finance , Tally , Tds , Accounting , A...","Remote Recruiter: As a remote Recruiter , you...",Jorhat,0 - 2 yrs
14,Priyanka Vinayak,"Finance , Tally , Tds , Accounting , A...",Protecting what matters most to our associates...,Dhubri,0 - 2 yrs
15,Priyanka Vinayak,"Finance , Tally , Tds , Accounting , A...","Digital Marketer: As a Digital Marketer , you...",Silchar,0 - 1 yrs
16,TECHNOPARK TRIVANDRU,"python , machine learning , opencv",Brief description :Machine learning Engineers ...,Thiruvananthapuram,3 - 4 yrs
17,Cybage Software Pvt Ltd,"python , java , machine learning","Experience: 6-9 YearsTo be the right fit , yo...",Pune,6 - 9 yrs
18,pattern effects labs private limited,"algorithms , machine learning , Boosting",Machine Learning AnalystLooking for machine le...,Bangalore,2 - 5 yrs
19,Vitrana,"algorithms , python , machine learning",Responsibilities:Study and transform data scie...,Bangalore,2 - 4 yrs
20,Cybage Software Pvt Ltd,"algorithms , python , java , machine lea...",Experience: 6 yearsThe key aspects of this ro...,Pune,6 - 9 yrs
21,e-con systems india pvt.ltd.,"algorithms , c , oops , machine learni...",Skillsets:Programming knowledge - Must be good...,Chennai,0 - 4 yrs
22,Cotocu,"machine learning , artificial intelligence ...",Job Description General RequirementPreferably ...,Bangalore,8 - 11 yrs
23,Cotocu,"machine learning , docker , data science",Job Description Autodesk is seeking a Machine ...,Bangalore,0 - 3 yrs
24,Nse IT Ltd,"algorithms , python , machine learning , ...",Desired Skills & ExperienceOutcomesIndepende...,Mumbai,2 - 3 yrs